config/routes.rb
Rails.application.routes.draw do

get 'signin', to: 'sessions#new'
post 'sessions', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'

post '/api/sms', to: 'twilio#sms'
get 'message', to: 'grubbers#alert'
get 'sent', to: 'grubbers#sent'

resources :grubbers, except: :index do
  collection do #got rid of the id requirement
    post 'message'
  end
end

  root 'grubbers#new'

end

app/models/grubber.rb
class Grubber < ActiveRecord::Base
	scope :subscribed, ->{where(subscribed: true) } 

	scope :emailable, ->{where(email_ok: true, subscribed: true)}
	scope :textable , ->{subscribed.where(text_ok: true)}
# wow Jason - sql?
	scope :find_grubber ->(params_key) {where'(email = ? or mobile = ?'), "#{params_key}", "#{params_key}" }

	validates :password, presence: true
	validates :email, uniqueness: true
	validates :mobile, uniqueness: true
#try this out! Franky
	validates :email, presence: { 
		message: "Must provide email or mobile number.",
			unless: Proc.new {|grubber| grubber.mobile.present?} }			
	validates :email, uniqueness: true
	validates :mobile, presence: {
		message: "Must provide email or mobile number." 
			unless: Proc.new {|grubber| grubber.email.present?} }
	validates :mobile, uniqueness: true

	# def either_email_or_mobile_present
	# 	if email.present?
	# end


	before_create :configure_new_grubber
	#before_validation :normalize_mobile

	# def normalize_mobile
	# 	self.mobile = GlobalPhone.noramlize(self.mobile)
	# end

	def configure_new_grubber
		self.subscribed = true
  		if self.mobile.present? 
  			self.text_ok = true
  		end

  		if self.email.present?
  			self.email_ok = true
  		end
	end 

	# def send_text(message_body)
	# 	# Get your Account Sid and Auth Token from twilio.com/user/account
	# 	# account_sid = ENV['???']
	# 	# auth_token = ENV['???']
	# 	# grubber_system_number = ENV['???']  Moved to initializers
		
	# 	# @client = Twilio::REST::Client.new account_sid, auth_token
	# 	@client = Twilio::REST::Client.new ENV['???'], ENV['???']  #grabbed from twilio initializer
 # 		mobile = self.mobile

	# 	#testing
	# 	puts "*" * 40
	# 	puts "mobile: #{mobile}"
	# 	puts "message: #{message_body}"


	# 	message = @client.account.messages.create(:body => message_body,
 #    		:to => mobile,
 #    		:from => grubber_system_number
	# 	puts message.to

	# end

	# def self.text_grubbers(message_body)
	# 	Grubber.textable.each do |grubber|
	# 		grubber.send_text(message_body)
	# 	end
	# end



	# def send_email(message_body) #instance method

	# 		recipient = [{email: self.email}]
	# 		m = Mandrill::API.new
	# 		message = {
	# 		:subject=> "Grub Alert",
	# 		:from_name=> "Grub Tracker",
	# 		:text=> message_body,
	# 		:to=>[ #emailable_grubbers          #recipient - for class method 
	# 		{  
	# 		:email=> "kenrickguie@gmail.com",
	# 		# :name=> "Ken"
	# 		}
	# 		],
	# 		:html=>"<html><h1>Hi <strong>#{message_body}</strong>, come now!</h1></html>",
	# 		:from_email=>"nyhunter77@gmail.com"
	# 		}
	# 		sending = m.messages.send message
	# 		puts sending

	# end  # gotta go over the instance method again ####################

	# 	def self.email_grubbers(message_body)  # instance is better(not self) - one email at a time to 1 recipient 
	# 	# m = Mandrill::API.new

	# 	Grubber.emailable.each do |grubber|
	# 		grubber.send_email(message_body)  
	# 	end
	# end

	def self.email_grubbers(message_body)  # this is class method - not a good idea, instance is better(not self) - one email at a time to 1 recipient 
		 m = Mandrill::API.new

		emailable_grubbers = Grubber.emailable.map do |grubber|  
			Hash(email: grubber.email) 
		end

		emailable_grubbers.each do |email|
			recipient = [email]
			#m = Mandrill::API.new
			message = {
			:subject=> "Grub Alert",
			:from_name=> "Grub Tracker",
			:text=> message_body,
			:to=>[ #emailable_grubbers          #recipient - for class method 
			{  
			:email=> "kenrickguie@gmail.com",
			# :name=> "Ken"
			}
			],
			:html=>"<html><h1>Hi <strong>#{message_body}</strong>, come now!</h1></html>",
			:from_email=>"nyhunter77@gmail.com"
			}
			sending = m.messages.send message
			puts sending

		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/grubbers_controller.rb
class GrubbersController < ApplicationController

	before_action :set_grubber

	def message
		#require 'mandrill'
		@message = params[:body]
		puts "*********** sending messages *************"

		Grubber.email_grubbers(message)

		#  ?????
		# Grubber.emailable.each do |grubber|
		# 	grubber.send_email(message)
		# end

		# Grubber.text_grubbers(message)

		# redirect_to message_grubbers_path
	end



  def sent 

  end

  def show
  end

  def new
  	@grubber = Grubber.new
  end

  def create
  	@grubber = Grubber.new(user_params)

  	# configure_new_grubber sets attributes in the grubber model
  	if @grubber.save
  		flash[:notice] = "Let's get grubbing"
  		redirect_to message_path
  	else
  		flash[:alert] = "Something went wrong"
  		render :new
  	end
  end

  def edit
  	
  end

  def update
  	if @grubber.update(grubber_params)
  		flash[:notice] = "Grubber successfully updated!"
  		redirect_to root_path
  	else
  		flash[:alert] = "Something went wrong with update!"
  		render :edit
  	end
  end

  private

  def user_params
  	params.require(:grubber).permit(:mobile, :email, :password, :email_ok, :text_ok, :subcribed)
  end

  def set_grubber
  	@grubber = Grubber.find(params[:id])
  end






end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationsController

	def new

	end

	def create
		# login = GlobalPhone.normalize(params(:email))
		# login = 

		@grubber = Grubber.find_by(email: params[:email]).first
			if @grubber && @grubber.password == params[:password]
				session[:grubber_id] = @grubber.id
				flash[:notice] = "You logged in Grubber!"
				redirect_to message_path
			else
				flash[:alert] = "Something went wrong."
				redirect_to root_path
			end
	end

	def destroy
		session[:grubber_id] = nil
		flash[:notice] = "You've logged out!"
		redirect_to root_path
	end

end

app/controllers/twilio_controller.rb
class TwilioController < ApplicationController

	skip_before_action :verify_authenticity_token

	def sms
		@message = params[:Body]
		grubber = Grubber.find_by_mobile(params[:From])
		if grubber
			Grubber.email_grubbers(message)
			Grubber.text_grubbers(message)
		end
		render status: :ok
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_grubber
		session[:grubber_id] ? Grubber.find(session[:grubber_id]) : nil
	end

end

app/helpers/grubbers_helper.rb
module GrubbersHelper
end

app/views/grubbers/alert.html.erb
<h1>Got an alert?</h1>

<% if current_grubber %>

<p> Let the world know below </p>

	<%= form_tag('/grubbers/message', method: :post) do%>
		<%= text_area_tag :body %>
		<%= submit_tag "Let's do this!" %>
	<% end %>

<% else %>
	<p> Please <%= link_to 'sign in', signin_path %> or <%= link_to 'sign up!', root_path %> </p>

<% end %>

app/views/grubbers/edit.html.erb
<h1>Welcome Grubber, Good to have you back! </h1>

<p> How would you like to be notified? Enter your email, mobile number, or both. </p>

<%=form_for @grubber do |f| %>
	<% if @grubber.errors.any? %>
		<ul>
		<% @grubber.errors.full_messages.each do |msg| %>
			<li> <%= msg %> </li>
		<% end %>
		</ul>
	<% end%>

	<%= f.label :email  %>
	<%= f.text_field :email %><br/>
	<%= f.check_box :email_ok %>
	<% if @grubber.email_ok %>
		<span class="detail"> (Uncheck to start email alerts) </span>
	<% else %>
		<span class="detail"> (Check to receive text alerts) </span>
	<% end %>

	<% if @grubber.text_ok %>
	<%= f.label :mobile %>
	<%= f.phone_field :mobile %><br/>
	<%= f.check_box :mobile_ok %>
	<span class="detail"> (receive texts?) </span><br/>

	<p class="detail"> Want to stop receiving alerts? Uncheck this box: </p>
	<% if @grubber.subscribed %>
		<%= f.check_box :subscribed %>

	<%= f.submit %>
<% end %>

app/views/grubbers/index.html.erb
<h1>Grubbers#index</h1>
<p>Find me in app/views/grubbers/index.html.erb</p>

app/views/grubbers/messages.html.erb
<h1>Message Sent </h1>
<p> Great job. Everyone Loves You </p>

app/views/grubbers/new.html.erb
<h1>Hello Future Grubber, I greet you!</h1>

<% if current_grubber %>
	<p> Want to send a message? </p>
<% else %>
<p> How would you like to be notified? Enter your email, mobile number, or both. </p>

<%=form_for @grubber do |f| %>
	<% if @grubber.errors.any? %>
		<ul>
		<% @grubber.errors.full_messages.each do |msg| %>
			<li> <%= msg %> </li>
		<% end %>
		</ul>
	<% end%>

	<%= f.label :email  %>
	<%= f.text_field :email %><br/>
	<%= f.label :mobile %>
	<%= f.phone_field :mobile %><br/>
	<%= f.label :password %>
	<%= f.password_field :password %><br/>
	<%= f.submit %>
<% end %>

app/views/grubbers/show.html.erb
<h1>Got an alert?</h1>

<p> Let the world know below </p>

	<%= form_tag('/grubbers/message', method: :post) %>
		<%= text_area_tag :body %>
		<%= submit_tag "Let's do this!" %>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pizza</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<nav> <%= render 'shared/login' %> </nav>

	</header>


<%= flash[:notice] if flash[:notice] %>
<%= flash[:alert] if flash[:alert] %>
<%= yield %>

</body>
</html>

app/views/shared/_login.html.erb
<% if current_grubber %>
	<p> Whatddap Grubber?  |  
	<%= link_to 'Sign-Out', logout_path, method: :destroy %> </p>  |  
	<%= link_to 'settings', edit_grubber_path(current_grubber) %> 
<% else %>

<% end %>

<%= form_tag '/sessions', method: :post do %>
	<%= label_tag :email, "Sign in" %>
	<%= text_field_tag :email, nil,  placeholder: "email or mobile" %>
	<%= label_tag :password %>
	<%= password_field_tag :password %>
	<%= submit_tag :login %>
<% end %>